apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  namespace: kubeflow
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared_volume"