kind: Service
apiVersion: v1
metadata:
        name: loadbalancer-opt-0-1-hostpath-pv
        namespace: kubeflow
spec:
        type: LoadBalancer
        ports:
                - port: 8888
                  targetPort: 8888
                  protocol: TCP
                  nodePort: 30001 #select port of your preference
        selector:
                app: jupyterlab-opt-0-1-hostpath-pv-app